version: "3"

services:
  api:
    build: .
    container_name: question-service-api
    ports:
      - "8080:8080"
    networks:
      - fullstack
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack  
    volumes:
      - database_postgres:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d

networks:
  fullstack:
    driver: bridge
volumes:
  database_postgres: